### ISSUE TITLE
not support promise ?

### ISSUE THREAD

**Issue by cheft** [StephanHoyer/mithril-node-render#28] opened 2015-12-22 07:36 UTC
not support promise ?

**Comment by StephanHoyer** [comment] 2015-12-22 07:36
can you be more specific please?

**Comment by cheft** [comment] 2015-12-23 02:01
Run the [mithril demo](http://mithril.js.org/index.html), throw error

         ctrl.pages().map(function(page) {
           ^
    TypeError: ctrl.pages is not a function

because ctrl.pages() is promise object, want to support!

**Comment by StephanHoyer** [comment] 2015-12-23 11:50
Can you please show the full code. I think the problem is unrelated to mithril-node-render

**Comment by StephanHoyer** [comment] 2016-04-13 10:35
Will close this for now.

Feel free to reopen, if this is still a problem.

**Closed by StephanHoyer** 2016-04-13 10:35 UTC
